# Blank

In [6]:
import torch as tt
from numpy.random import default_rng
rng = default_rng(12)


In [7]:
in_dim ,out_dim = 4, 3
batch_size = 500

x_data, y_data = rng.random(size=(batch_size, in_dim,)),  rng.random(size=(batch_size, out_dim,)), 

x = tt.zeros((batch_size, in_dim,), dtype=tt.float32)
x.copy_(tt.tensor(x_data))

y = tt.zeros((batch_size, out_dim,), dtype=tt.float32)
y.copy_(tt.tensor(y_data))

x.shape, y.shape, x, y

(torch.Size([500, 4]),
 torch.Size([500, 3]),
 tensor([[0.2508, 0.9468, 0.1893, 0.1793],
         [0.3499, 0.2305, 0.6704, 0.1151],
         [0.8963, 0.8581, 0.0028, 0.5415],
         ...,
         [0.3004, 0.7876, 0.7642, 0.7006],
         [0.7372, 0.8800, 0.9546, 0.7862],
         [0.2122, 0.2075, 0.8401, 0.4433]]),
 tensor([[0.4158, 0.3538, 0.4710],
         [0.4563, 0.2655, 0.8062],
         [0.3518, 0.3223, 0.6932],
         ...,
         [0.4134, 0.6258, 0.5769],
         [0.3654, 0.7622, 0.9985],
         [0.4546, 0.2451, 0.0407]]))

In [8]:

w = tt.zeros((out_dim, in_dim), dtype=tt.float32, requires_grad=True)
b = tt.zeros((out_dim,), dtype=tt.float32, requires_grad=True)


w.shape, b.shape, in_dim ,out_dim 

(torch.Size([3, 4]), torch.Size([3]), 4, 3)

In [9]:
def zero_grad():
    w.grad=None
    b.grad=None

def show_grad():
    print(w.grad, b.grad)

def step( lr):
    with tt.no_grad():
        global w, b
        w -= lr*w.grad
        b -= lr*b.grad



def forward(w,b,x):
    return w @ x + b

def f1(w,b,X):
    return  tt.stack([ (w @ x + b ) for x in X ])


def f2(w,b,X):
    return (w @ x.T).T + b

def mse(pred, truth):
    return tt.mean((pred - y)**2)

def se(pred, truth):
    return (pred - y)**2

In [10]:
w, b

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]], requires_grad=True),
 tensor([0., 0., 0.], requires_grad=True))

In [14]:
for _ in range(1000):
    pred = f2(w, b, x)
    loss = mse(pred, y)
    zero_grad() 
    loss.backward() #<--- zero_grad()  any where before this
    step(0.001)     #<---  zero_grad() any where after this
#zero_grad() 


In [12]:
w, b

(tensor([[0.0928, 0.0898, 0.0851, 0.0950],
         [0.0861, 0.0878, 0.0882, 0.0913],
         [0.0853, 0.0904, 0.0874, 0.0941]], requires_grad=True),
 tensor([0.1846, 0.1789, 0.1788], requires_grad=True))